In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ML-EDA.csv to ML-EDA.csv

In [3]:
import pandas as pd

# Replace 'your_file.csv' with the uploaded file name
Animal_data = pd.read_csv('ML-EDA.csv')
Animal_data

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25

In [4]:
Animal_data.head(5)

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

In [5]:
Animal_data.tail(3)

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25

In [6]:
Animal_data.shape

(205, 16)

In [7]:
print("number of rows = ",Animal_data.shape[0])

number of rows =  205

In [8]:
print("number of columns = ",Animal_data.shape[1])

number of columns =  16

In [9]:
Animal_data.columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [10]:
Animal_data.dtypes

Animal                     object
Height (cm)                object
Weight (kg)                object
Color                      object
Lifespan (years)           object
Diet                       object
Habitat                    object
Predators                  object
Average Speed (km/h)       object
Countries Found            object
Conservation Status        object
Family                     object
Gestation Period (days)    object
Top Speed (km/h)           object
Social Structure           object
Offspring per Birth        object
dtype: object

In [11]:
Animal_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Animal                   205 non-null    object
 1   Height (cm)              205 non-null    object
 2   Weight (kg)              205 non-null    object
 3   Color                    205 non-null    object
 4   Lifespan (years)         205 non-null    object
 5   Diet                     205 non-null    object
 6   Habitat                  205 non-null    object
 7   Predators                205 non-null    object
 8   Average Speed (km/h)     205 non-null    object
 9   Countries Found          205 non-null    object
 10  Conservation Status      205 non-null    object
 11  Family                   205 non-null    object
 12  Gestation Period (days)  205 non-null    object
 13  Top Speed (km/h)         205 non-null    object
 14  Social Structure         205 non-null    object
 15  Offspring per Birth      205 non-null    object
dtypes: object(16)
memory usage: 25.8+ KB

In [12]:
Animal_data.head(2)

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5

In [13]:
Animal_tab1 = Animal_data[['Animal','Color','Family','Diet']]
Animal_tab1.head(3)

             Animal         Color           Family         Diet
0          Aardvark          Grey  Orycteropodidae  Insectivore
1          Aardwolf  Yellow-brown        Hyaenidae  Insectivore
2  African Elephant          Grey     Elephantidae    Herbivore

In [14]:
Animal_tab3 = Animal_data.drop(columns=['Color','Diet'], axis = 1)
Animal_tab3

,Animal,Height (cm),Weight (kg),Lifespan (years),Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,20-30,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,10-12,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,60-70,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,10-14,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,10-12,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,20-25,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50
201,Yellow-Eyed Penguin,60-65,1-3,Up to 20,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1
202,Yeti Crab,Up to 15,Up to 0.5,Up to 20,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable
203,Zebra,220-340,400-900,20-25,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
204,Zebra Shark,Up to 330,Up to 32,25-30,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25

In [15]:
Animal_tab3['Dataset']= 'Animal_Dataset'
Animal_tab3

,Animal,Height (cm),Weight (kg),Lifespan (years),Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth,Dataset
0,Aardvark,105-130,40-65,20-30,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1,Animal_Dataset
1,Aardwolf,40-50,8-14,10-12,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5,Animal_Dataset
2,African Elephant,270-310,2700-6000,60-70,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1,Animal_Dataset
3,African Lion,80-110,120-250,10-14,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually),Animal_Dataset
4,African Wild Dog,75-80,18-36,10-12,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12,Animal_Dataset
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,20-25,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50,Animal_Dataset
201,Yellow-Eyed Penguin,60-65,1-3,Up to 20,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1,Animal_Dataset
202,Yeti Crab,Up to 15,Up to 0.5,Up to 20,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable,Animal_Dataset
203,Zebra,220-340,400-900,20-25,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20,Animal_Dataset
204,Zebra Shark,Up to 330,Up to 32,25-30,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25,Animal_Dataset

In [16]:
Animal_data.columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [17]:
col_dict = {'Animal' : 'animal',
            'Height (cm)' : 'Height_cm',
           'Weight (kg)' : 'Weight_kg' ,
            'Color' : 'Colour',
            'Lifespan (years)' : 'Lifespan_years',
           'Countries Found' : 'Countries_Found',
           'Conservation Status' : 'Conservation_Status' }

In [18]:
Animal_data = Animal_data.rename(columns = col_dict)
Animal_data.head(5)

,animal,Height_cm,Weight_kg,Colour,Lifespan_years,Diet,Habitat,Predators,Average Speed (km/h),Countries_Found,Conservation_Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

In [19]:
Animal_data.select_dtypes(include = 'object').head()

,animal,Height_cm,Weight_kg,Colour,Lifespan_years,Diet,Habitat,Predators,Average Speed (km/h),Countries_Found,Conservation_Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

In [20]:
Animal_data.select_dtypes(exclude = 'object').head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [21]:
Categorical_col = Animal_data.select_dtypes(include = 'object').columns
Categorical_col

Index(['animal', 'Height_cm', 'Weight_kg', 'Colour', 'Lifespan_years', 'Diet',
       'Habitat', 'Predators', 'Average Speed (km/h)', 'Countries_Found',
       'Conservation_Status', 'Family', 'Gestation Period (days)',
       'Top Speed (km/h)', 'Social Structure', 'Offspring per Birth'],
      dtype='object')

In [22]:
Numerical_col = Animal_data.select_dtypes(exclude = 'object').columns
Numerical_col

Index([], dtype='object')

In [23]:
Cat_df = Categorical_col = Animal_data.select_dtypes(include = 'object')
Cat_df

,animal,Height_cm,Weight_kg,Colour,Lifespan_years,Diet,Habitat,Predators,Average Speed (km/h),Countries_Found,Conservation_Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25

In [24]:
num_df = Categorical_col = Animal_data.select_dtypes(exclude = 'object')
num_df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[205 rows x 0 columns]

In [25]:
Categorical_col_list = list(Animal_data.select_dtypes(include = 'object').columns)
Categorical_col_list

['animal',
 'Height_cm',
 'Weight_kg',
 'Colour',
 'Lifespan_years',
 'Diet',
 'Habitat',
 'Predators',
 'Average Speed (km/h)',
 'Countries_Found',
 'Conservation_Status',
 'Family',
 'Gestation Period (days)',
 'Top Speed (km/h)',
 'Social Structure',
 'Offspring per Birth']

In [26]:
Numerical_col_list = list(Animal_data.select_dtypes(exclude = 'object').columns)
Numerical_col_list

[]

In [27]:
# checking the duplicate record
Animal_data.duplicated().any()

np.False_

In [28]:

Animal_data.duplicated().sum()

np.int64(0)

In [29]:
# display the deuplicate records
Animal_data[Animal_data.duplicated()]

Empty DataFrame
Columns: [animal, Height_cm, Weight_kg, Colour, Lifespan_years, Diet, Habitat, Predators, Average Speed (km/h), Countries_Found, Conservation_Status, Family, Gestation Period (days), Top Speed (km/h), Social Structure, Offspring per Birth]
Index: []

In [30]:
Animal_data2 = Animal_data.drop_duplicates()

In [31]:
Animal_data2.shape

(205, 16)

In [32]:
Animal_data2.duplicated().any()

np.False_

In [33]:
#iNDEXING  the columns
df = Animal_data2.isnull().sum().reset_index()
#Rename the column
df.columns = ['column', 'null_records']
#Create the new columns and give out the null value percentage
df['% null_records'] = (df['null_records']/11199)*100
df

                     column  null_records  % null_records
0                    animal             0             0.0
1                 Height_cm             0             0.0
2                 Weight_kg             0             0.0
3                    Colour             0             0.0
4            Lifespan_years             0             0.0
5                      Diet             0             0.0
6                   Habitat             0             0.0
7                 Predators             0             0.0
8      Average Speed (km/h)             0             0.0
9           Countries_Found             0             0.0
10      Conservation_Status             0             0.0
11                   Family             0             0.0
12  Gestation Period (days)             0             0.0
13         Top Speed (km/h)             0             0.0
14         Social Structure             0             0.0
15      Offspring per Birth             0             0.0

In [34]:
Animal_data2.head()

,animal,Height_cm,Weight_kg,Colour,Lifespan_years,Diet,Habitat,Predators,Average Speed (km/h),Countries_Found,Conservation_Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12