In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
from google.colab import files
uploaded = files.upload()

Saving ML-Dataset.csv to ML-Dataset (1).csv

In [15]:
import pandas as pd

# Replace 'your_file.csv' with the uploaded file name
Product_data = pd.read_csv('ML-Dataset.csv')
Product_data

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,Lithium Battery,200,4998.0,5999.0,16.0
...,...,...,...,...,...,...,...,...
816,Swa Mi Drone WiFi Camera Remote Control-Motion...,Professional Drone,60,Lithium Battery,250,2244.0,8999.0,75.0
817,Radhikadro e449 Drone,Professional Drone,100,Lithium Battery,350,2447.0,4999.0,51.0
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,102,Lithium Battery,400,1799.0,6999.0,74.0
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,60,Lithium Battery,250,2799.0,5999.0,53.0
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,100,Lithium Battery,300,2705.0,8999.0,69.0

In [16]:
Product_data.head(5)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,Lithium Battery,200,4998.0,5999.0,16.0

In [17]:
Product_data.tail(3)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,102,Lithium Battery,400,1799.0,6999.0,74.0
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,60,Lithium Battery,250,2799.0,5999.0,53.0
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,100,Lithium Battery,300,2705.0,8999.0,69.0

In [18]:
Product_data.shape

(821, 8)

In [19]:
print("number of rows = ",Product_data.shape[0])

number of rows =  821

In [20]:
print("number of columns = ",Product_data.shape[0])

number of columns =  821

In [21]:
Product_data.columns

Index(['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price', 'Discount (%)'],
      dtype='object')

In [22]:
Product_data.dtypes

Name              object
Type              object
Control Range      int64
Battery Type      object
Weight             int64
Price            float64
Actual Price     float64
Discount (%)     float64
dtype: object

In [23]:
Product_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 821 entries, 0 to 820
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           821 non-null    object
 1   Type           821 non-null    object
 2   Control Range  821 non-null    int64
 3   Battery Type   821 non-null    object
 4   Weight         821 non-null    int64
 5   Price          813 non-null    float64
 6   Actual Price   813 non-null    float64
 7   Discount (%)   810 non-null    float64
dtypes: float64(3), int64(2), object(3)
memory usage: 51.4+ KB

In [24]:
Product_data.head(2)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0

In [25]:
Product_tab1 = Product_data[['Name','Type','Battery Type']]
Product_tab1.head(3)

,Name,Type,Battery Type
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,Lithium Battery
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,AA Battery
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,AA Rechargeable Battery

In [26]:
Product_tab3 = Product_data.drop(columns=['Name','Type'], axis = 1)
Product_tab3

,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
0,40,Lithium Battery,200,2297.0,4999.0,54.0
1,300,AA Battery,500,10255.0,11000.0,6.0
2,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,50,Lithium Battery,150,2455.0,4999.0,50.0
4,200,Lithium Battery,200,4998.0,5999.0,16.0
...,...,...,...,...,...,...
816,60,Lithium Battery,250,2244.0,8999.0,75.0
817,100,Lithium Battery,350,2447.0,4999.0,51.0
818,102,Lithium Battery,400,1799.0,6999.0,74.0
819,60,Lithium Battery,250,2799.0,5999.0,53.0
820,100,Lithium Battery,300,2705.0,8999.0,69.0

In [27]:
Product_tab3['Dataset']= 'Product_Dataset'
Product_tab3

,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%),Dataset
0,40,Lithium Battery,200,2297.0,4999.0,54.0,Product_Dataset
1,300,AA Battery,500,10255.0,11000.0,6.0,Product_Dataset
2,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0,Product_Dataset
3,50,Lithium Battery,150,2455.0,4999.0,50.0,Product_Dataset
4,200,Lithium Battery,200,4998.0,5999.0,16.0,Product_Dataset
...,...,...,...,...,...,...,...
816,60,Lithium Battery,250,2244.0,8999.0,75.0,Product_Dataset
817,100,Lithium Battery,350,2447.0,4999.0,51.0,Product_Dataset
818,102,Lithium Battery,400,1799.0,6999.0,74.0,Product_Dataset
819,60,Lithium Battery,250,2799.0,5999.0,53.0,Product_Dataset
820,100,Lithium Battery,300,2705.0,8999.0,69.0,Product_Dataset

In [28]:
Product_data.columns

Index(['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price', 'Discount (%)'],
      dtype='object')

In [29]:
col_dict = {'Name' : 'name',
           'Type' : 'type',
           'Control Range' : 'Control_Range',
            'Battery_Type' : 'Battery_Type',
           'Actual Price' : 'Actual_Price' }

In [30]:
Product_data = Product_data.rename(columns = col_dict)
Product_data.head(5)

,name,type,Control_Range,Battery Type,Weight,Price,Actual_Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,Lithium Battery,200,4998.0,5999.0,16.0

In [31]:
Product_data.select_dtypes(include = 'object').head()

,name,type,Battery Type
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,Lithium Battery
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,AA Battery
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,AA Rechargeable Battery
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,Lithium Battery
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,Lithium Battery

In [32]:
Product_data.select_dtypes(exclude = 'object').head()

   Control_Range  Weight    Price  Actual_Price  Discount (%)
0             40     200   2297.0        4999.0          54.0
1            300     500  10255.0       11000.0           6.0
2            102     150   1994.0        5999.0          66.0
3             50     150   2455.0        4999.0          50.0
4            200     200   4998.0        5999.0          16.0

In [33]:
Categorical_col = Product_data.select_dtypes(include = 'object').columns
Categorical_col

Index(['name', 'type', 'Battery Type'], dtype='object')

In [34]:
Numerical_col = Product_data.select_dtypes(exclude = 'object').columns
Numerical_col

Index(['Control_Range', 'Weight', 'Price', 'Actual_Price', 'Discount (%)'], dtype='object')

In [35]:
Cat_df = Categorical_col = Product_data.select_dtypes(include = 'object')
Cat_df

,name,type,Battery Type
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,Lithium Battery
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,AA Battery
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,AA Rechargeable Battery
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,Lithium Battery
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,Lithium Battery
...,...,...,...
816,Swa Mi Drone WiFi Camera Remote Control-Motion...,Professional Drone,Lithium Battery
817,Radhikadro e449 Drone,Professional Drone,Lithium Battery
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,Lithium Battery
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,Lithium Battery
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,Lithium Battery

In [36]:
num_df = Categorical_col = Product_data.select_dtypes(exclude = 'object')
num_df

     Control_Range  Weight    Price  Actual_Price  Discount (%)
0               40     200   2297.0        4999.0          54.0
1              300     500  10255.0       11000.0           6.0
2              102     150   1994.0        5999.0          66.0
3               50     150   2455.0        4999.0          50.0
4              200     200   4998.0        5999.0          16.0
..             ...     ...      ...           ...           ...
816             60     250   2244.0        8999.0          75.0
817            100     350   2447.0        4999.0          51.0
818            102     400   1799.0        6999.0          74.0
819             60     250   2799.0        5999.0          53.0
820            100     300   2705.0        8999.0          69.0

[821 rows x 5 columns]

In [37]:
Categorical_col_list = list(Product_data.select_dtypes(include = 'object').columns)
Categorical_col_list

['name', 'type', 'Battery Type']

In [38]:
Numerical_col_list = list(Product_data.select_dtypes(exclude = 'object').columns)
Numerical_col_list

['Control_Range', 'Weight', 'Price', 'Actual_Price', 'Discount (%)']

In [39]:
# checking the duplicate record
Product_data.duplicated().any()

np.True_

In [40]:
Product_data.duplicated().sum()

np.int64(3)

In [41]:
# display the deuplicate records
Product_data[Product_data.duplicated()]

,name,type,Control_Range,Battery Type,Weight,Price,Actual_Price,Discount (%)
478,Swa Mi E88 Pro Foldable Remote Control Drone D...,Professional Drone,100,Lithium Battery,100,2705.0,8999.0,69.0
609,Swa Mi Mini dron with Camera Hd Dual Camera Wi...,Professional Drone,100,Lithium Battery,100,2244.0,8999.0,75.0
630,"Swa Mi High Quality E88 Pro Drone HD, Dual Cam...",Professional Drone,100,Lithium Battery,100,2705.0,8999.0,69.0

In [42]:
Product_data2 = Product_data.drop_duplicates()

In [44]:
Product_data.shape

(821, 8)

In [45]:
Product_data2.duplicated().any()

np.False_

In [46]:
#iNDEXING  the columns
df = Product_data2.isnull().sum().reset_index()
#Rename the column
df.columns = ['column', 'null_records']
#Create the new columns and give out the null value percentage
df['% null_records'] = (df['null_records']/11199)*100
df

          column  null_records  % null_records
0           name             0        0.000000
1           type             0        0.000000
2  Control_Range             0        0.000000
3   Battery Type             0        0.000000
4         Weight             0        0.000000
5          Price             8        0.071435
6   Actual_Price             8        0.071435
7   Discount (%)            11        0.098223

In [47]:
Product_data.head(2)

,name,type,Control_Range,Battery Type,Weight,Price,Actual_Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0

In [48]:
# display the deuplicate records
Product_data[Product_data.duplicated()]

,name,type,Control_Range,Battery Type,Weight,Price,Actual_Price,Discount (%)
478,Swa Mi E88 Pro Foldable Remote Control Drone D...,Professional Drone,100,Lithium Battery,100,2705.0,8999.0,69.0
609,Swa Mi Mini dron with Camera Hd Dual Camera Wi...,Professional Drone,100,Lithium Battery,100,2244.0,8999.0,75.0
630,"Swa Mi High Quality E88 Pro Drone HD, Dual Cam...",Professional Drone,100,Lithium Battery,100,2705.0,8999.0,69.0

In [49]:
Product_data2 = Product_data.drop_duplicates()

In [50]:
Product_data2['name']

0      Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...
1      Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...
2      Clubmall E88 Pro 4K Camera Drone with WiFi FPV...
3      Orivox A17 Aerial Drone with 4K Dual Camera - ...
4      Orivox M3 Max Mini Drone with Pro Features HD ...
                             ...
816    Swa Mi Drone WiFi Camera Remote Control-Motion...
817                                Radhikadro e449 Drone
818    Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...
819    mayuri E8 WiFi Camera Remote Control 360 Flip ...
820    Swa Mi E88 Drone Best Adults/Kids Drone With W...
Name: name, Length: 818, dtype: object

In [51]:
mode_name = Product_data2['name'].mode()[0]
mode_name

'Swa Mi Drone WiFi Camera Drone Remote Control Quadcopter 360 Flip Stunt Drone1 Drone'

In [52]:
Product_data2['name'].value_counts()

name
Swa Mi Drone WiFi Camera Drone Remote Control Quadcopter 360 Flip Stunt Drone1 Drone    7
Swa Mi Drone WiFi Camera Remote Control Quadcopter 360 Flip Stunt Drone1 Drone          3
Swa Mi Drone WiFi Camera Remote Control Quadcopter 360 Flip Stunt1 Drone                3
Swa Mi Quadcopter E88 Drone With Wide Angle HD Camera Height Hold Foldable1 Drone       2
Swa Mi E88 Pro Drone Wide Angle Dual 4K HD Cameras with two Smart battery1 Drone        2
                                                                                       ..
Barbie dronRemote Control Quadcopter 360 Flip Stunt_a8b Drone                           1
Barbie E88-Drone - Black_5b Drone                                                       1
Barbie Foldable Remote Control Drone with Camera HD Wide Angle Lens_18b Drone           1
Barbie ad172drone3b Drone                                                               1
Barbie Blue Quadcopter Drone_15b Drone                                                  1
Name: count, Length: 797, dtype: int64

In [54]:
Product_data2['type'].value_counts()

type
Professional Drone    427
Mini Drone            391
Name: count, dtype: int64

In [55]:
Product_data2['name'] = Product_data2['name'].fillna(mode_name)

/tmp/ipykernel_10086/2932877973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Product_data2['name'] = Product_data2['name'].fillna(mode_name)

In [56]:
Product_data2.isnull().sum()

name              0
type              0
Control_Range     0
Battery Type      0
Weight            0
Price             8
Actual_Price      8
Discount (%)     11
dtype: int64

In [61]:
Price_mean = Product_data2['Price'].mean()
Product_data2['Price'] = Product_data2['Price'].fillna(Price_mean)

/tmp/ipykernel_10086/1959764243.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Product_data2['Price'] = Product_data2['Price'].fillna(Price_mean)

In [62]:
Product_data2.isnull().sum()

name              0
type              0
Control_Range     0
Battery Type      0
Weight            0
Price             0
Actual_Price      0
Discount (%)     11
Product           0
dtype: int64

In [59]:
Actual_Price_mean = Product_data2['Actual_Price'].mean()
Product_data2['Actual_Price'] = Product_data2['Actual_Price'].fillna(Actual_Price_mean)

/tmp/ipykernel_10086/1905330224.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Product_data2['Actual_Price'] = Product_data2['Actual_Price'].fillna(Actual_Price_mean)

In [63]:
Product_data2.isnull().sum()

name              0
type              0
Control_Range     0
Battery Type      0
Weight            0
Price             0
Actual_Price      0
Discount (%)     11
Product           0
dtype: int64

In [65]:
Discount_mean = Product_data2['Discount (%)'].mean()
Product_data2['Discount (%)'] = Product_data2['Discount (%)'].fillna(Discount_mean)

/tmp/ipykernel_10086/3477054433.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Product_data2['Discount (%)'] = Product_data2['Discount (%)'].fillna(Discount_mean)

In [66]:
Product_data2.isnull().sum()

name             0
type             0
Control_Range    0
Battery Type     0
Weight           0
Price            0
Actual_Price     0
Discount (%)     0
Product          0
dtype: int64